<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Fantastik.aspx.cs" Inherits="FinalProject.Fantastik" MasterPageFile="~/Site2.Master"  %>

<asp:Content ID="Content1" runat="server" contentplaceholderid="ContentPlaceHolder1">
    <p>

        <i style="color: rgb(105, 36, 6); font-family: Calibri; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b>Fantastik Kitaplar</b></i></p>
<p>

    <b style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Yüzüklerin Efendisi - J.R.R. Tolkien</b></p>
</asp:Content>
<asp:Content ID="Content2" runat="server" contentplaceholderid="ContentPlaceHolder7">
    <p>

        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Yüzüklerin Efendisi (&#304;ng. The Lord of the Rings) &#304;ngiliz dilbilimcisi Profesör J. R. R. Tolkien&#8217;in yazd&#305;&#287;&#305; Fantastik bir romand&#305;r. Hikâye Tolkien&#8217;in 1937 tarihli ve çocuklar için yazd&#305;&#287;&#305; Hobbit adl&#305; eserinin devam&#305; olarak yaz&#305;lmak istenmesiyle ortaya ç&#305;km&#305;&#351;t&#305;r. Roman 1937 ve 1949 y&#305;llar&#305; aras&#305;nda a&#351;amalar halinde yaz&#305;lm&#305;&#351; bas&#305;ld&#305;ktan sonra. 150 milyonun üstündeki sat&#305;&#351; elde ederek tüm zamanlar&#305;n en çok satan ikinci roman&#305; olmu&#351;tur.Bu eser destans&#305; ve masals&#305; 
        motifleri kullanmas&#305;na ra&#287;men mitlerle ve di&#287;er dünya destanlar&#305; aras&#305;ndaki alakas&#305; üzerinde çe&#351;itli görü&#351;ler de ileri sürülmü&#351;tür. Dünya destanlar&#305;ndan ve masallar&#305;ndan izler ta&#351;&#305;mas&#305;na ra&#287;men, yap&#305;t&#305;n belli destanlar&#305; ve mitleri malzame olarak kulland&#305;&#287;&#305; da söylenemez. Buna ra&#287;men ara&#351;t&#305;rmac&#305;lar&#305;n izahatlar&#305;na göre Tolk&#305;en&#8217;in bu eserini olu&#351;tururken peri hikâyeleri, &#304;skandinav ve Germen mitolojisi, ayr&#305;ca Kelt, Slav, Pers, Yunan ve Fin mitolojisi hakk&#305;ndaki bilgileri kullanm&#305;&#351;t&#305;r. Buna ra&#287;men eserin arka plan&#305;ndan hiç bir din ve inanc&#305;n telkinleri bulunmamaktad&#305;r. Eserdeki mekânlar ve toplumlar tamamen hayalidir. Tolk&#305;en her &#351;eyi ile hayali olan toplumlar, kültürler, devletler ve co&#287;rafyalar tasarlam&#305;&#351;; eserdeki mekânlar&#305;nda fantastik bir dünya olu&#351;turmu&#351;tur. San&#305;lanlar&#305;n ve iddia edilenlerin aksine Tolk&#305;en&#8217;nin de ifade etti&#287;i gibi eser alegorik olarak da hiç bir kültürü veya toplumu ima etmemektedir. Tolkien masallar&#305;n temel özelli&#287;i olan çok zay&#305;flar&#305;n çok güçlülere kar&#351;&#305; ba&#351;armak 
        zorunda kald&#305;klar&#305; ödevlerle kar&#351;&#305; kar&#351;&#305;ya kalmalar&#305;, iyilerle kötülerin çat&#305;&#351;mas&#305; masal kurgusunu bu eserinde kullanm&#305;&#351;, iyileri çok iyi; kötüleri çok kötü kal&#305;plarla aktarm&#305;&#351;t&#305;r. Bu masal yap&#305;s&#305;, romandaki &#305;rklar&#305;n ve tiplemelerin ana özelli&#287;ini olu&#351;turur. Elfler, Cüceler, Hobbitler, Haradrimler , Orklar ve di&#287;er &#305;rklar bu masals&#305; yakla&#351;&#305;mla tamamen iyiler veya tamamen kötüler olarak davranmaktad&#305;rlar. Roman masals&#305; planlar ve yakla&#351;&#305;mlar içinde yaz&#305;lm&#305;&#351; bir romand&#305;r.</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(Kitap fiyat&#305; hakk&#305;nda bilgi sahibi olmak için kitap görselini t&#305;klayabilirsiniz.)</span></p>
</asp:Content>
<asp:Content ID="Content3" runat="server" contentplaceholderid="ContentPlaceHolder3">
    <p>

        <b style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Bitmeyecek Öykü - Michael Ende</b></p>
</asp:Content>
<asp:Content ID="Content4" runat="server" contentplaceholderid="ContentPlaceHolder6">
    <p>

        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Michael Ende, 1979&#8217;da &#8220;Bitmeyecek Öykü&#8221; adl&#305; genç-yeti&#351;kin kitab&#305;n&#305; yazar. On milyon sat&#305;&#351;la ba&#351;ar&#305;n&#305;n zirvesine t&#305;rman&#305;r Michael Ende. Eser 40 dile çevrilir. &#8220;Kitaplar&#305;m&#305; içindeki çocu&#287;u ya&#351;atan herkes için de yaz&#305;yorum,&#8221; cümlesini tasdikler &#351;ekilde, yeti&#351;kinlerce de ra&#287;bet görür ve ça&#287;da&#351; edebiyat klasikleri aras&#305;nda yerini al&#305;r. 1984 senesinde film uyarlamas&#305;yla sinema perdelerine ta&#351;&#305;n&#305;r. Ne var ki bu durum yazar&#305; büyük bir hayal k&#305;r&#305;kl&#305;&#287;&#305;na u&#287;rat&#305;r. Çünkü kitap 
        ile filmi aras&#305;nda uçurumlar vard&#305;r. &#8220;Kitab&#305;n verdi&#287;i mesaj yok say&#305;lm&#305;&#351;, geriye yapmac&#305;kl&#305;kla ve yapayl&#305;kla dolu bir melodram sergilenmi&#351;,&#8221; &#351;eklinde dile getirir üzüntüsünü ve tepkisini. Bir çok yasal yola ba&#351;vursa da filmin önüne geçememi&#351;, sonras&#305;nda da ad&#305;n&#305;n filmden çekilmesini istemi&#351;tir. &#350;imdi gelelim eserin kendisine, &#350;i&#351;man, gözlüklü, okuldaki arkada&#351;lar&#305; taraf&#305;ndan sürekli tartaklan&#305;p alaya al&#305;nan on ya&#351;&#305;ndaki hayalperest bir kitapseverdir Bastian Balthasar Bux. Hayat onun için zorluklar&#305;n&#305; erken göstermi&#351;tir; annesini en ihtiyaç duyaca&#287;&#305; zamanda kaybetmi&#351; ve babas&#305; da e&#351;inin kayb&#305;yla kendi dünyas&#305;na çekilmi&#351;tir. Anne &#351;efkatinin eksikli&#287;i ve ilgisiz bir baban&#305;n duyars&#305;zl&#305;&#287;&#305; Bastian&#8217;&#305; özgüveni olmayan, korkak bir çocu&#287;a dönü&#351;türmü&#351;tür. Okurlar&#305;n kar&#351;&#305;s&#305;na da böyle bir atmosferde ç&#305;k&#305;verir. Bu hallet-i ruhiyesiyle ba&#351;lad&#305;&#287;&#305; bir okul gününde s&#305;n&#305;f arkada&#351;lar&#305;n&#305;n onu dövmek için arkas&#305;ndan kovalamas&#305;yla, küçük arkada&#351;&#305;m&#305;z da hikayesine ko&#351;ar ad&#305;mlarla giri&#351; yapar.</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Yazar, kahraman&#305;m&#305;z için bir kimlik aray&#305;&#351;&#305; niteli&#287;i ta&#351;&#305;yan bu serüvende bir çocu&#287;un dünyas&#305; vas&#305;tas&#305;yla insandaki gelgitleri, alm&#305;&#351; oldu&#287;u karalar&#305;n sonuçlar&#305;n&#305;n bedellerini, istekleri u&#287;runda kaybettiklerinin tekrar kazan&#305;m&#305;n&#305;n zorlu&#287;unu olay örgüsüne ba&#351;ar&#305;l&#305; &#351;ekilde yans&#305;tm&#305;&#351;. Michael Ende&#8217;nin hayat&#305;ndan da gördü&#287;ümüz gibi o da zorlu bir zaman&#305;n çocu&#287;u olarak büyümü&#351;tür. Zorbal&#305;klar&#305;n, ay&#305;r&#305;mlar&#305;n ve zulmülerin oldu&#287;u bir zamana &#351;ahitlik etmi&#351;, büyüklerin 
        dünyas&#305;n&#305;n ac&#305;mas&#305;zl&#305;&#287;&#305;n&#305; çocuk ya&#351;&#305;yla sindirmi&#351;tir. Hem Bitmeyecek Öykü&#8216;de hem de Momo&#8216;da yaln&#305;z, içine kapan&#305;k bir çocuk figürüyle kar&#351;&#305;m&#305;za ç&#305;kan yazar, bir nevi çocuklu&#287;unun tekli&#287;ini ve iç dünyas&#305;ndaki mücadeleleri bizlerle payla&#351;&#305;yor asl&#305;nda. Kötülüklerin ve y&#305;k&#305;mlar&#305;n kar&#351;&#305;s&#305;na çocuk masumiyetinin ve dostluklar&#305;n verdi&#287;i güçle ç&#305;k&#305;yor. &#304;nsan&#305;n hayat yolunda olan de&#287;i&#351;imini fantastik ve simgesel ögelerle i&#351;lerken her ya&#351;tan insan&#305;n okudu&#287;unda kendinden bir parça bulaca&#287;&#305; mesajlar veriyor kitaplar&#305;nda. Ressam bir baban&#305;n çocu&#287;u olmas&#305; da üretti&#287;i renkli dünyalarda ve karakterlerde kendini bir hayli gösteriyor.</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(Kitap fiyat&#305; hakk&#305;nda bilgi sahibi olmak için kitap görselini t&#305;klayabilirsiniz.)</span></p>
</asp:Content>
<asp:Content ID="Content5" runat="server" contentplaceholderid="ContentPlaceHolder4">
    <p>

        <b style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Bir &#304;z B&#305;rak - Veronica Roth</b></p>
</asp:Content>
<asp:Content ID="Content6" runat="server" contentplaceholderid="ContentPlaceHolder5">
    <p>

        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Kitab&#305;n ana konusu birbirlerinden iki farkl&#305; topluma mensup Cyra ve Akos&#39;un ba&#351;&#305;ndan geçenler. Thuve&#39;li bir çiftçi ve kahinin o&#287;lu olan Akos, a&#287;abeyi ile birlikte zalim Shotet halk&#305; taraf&#305;ndan kaç&#305;r&#305;l&#305;r. Shotet halk&#305;n&#305;n lideri Ryzek&#39;in k&#305;zkarde&#351;i Cyra herkesin özel güçlere sahip oldu&#287;u bu hikaye evreninin &#351;anss&#305;z&#305;d&#305;r. Ak&#305;m arma&#287;an&#305; ona dokunan herkesin muazzam bir ac&#305; çekmesini sa&#287;lamakla birlikte kendisine de ac&#305; vermektedir. &#304;nsanlar&#305;n ak&#305;m arama&#287;an&#305;n&#305; kesme gücüne 
        sahip olan Akos ac&#305;s&#305;n&#305; dindirmek için hizmetine verildi&#287;inde ikisinin de hayat&#305;nda beklenmedik de&#287;i&#351;iklikler olacakt&#305;r. Cyra&#39;n&#305;n Akos&#39;u hiçbir zaman köle olarak görmeyip adam yerine koymas&#305; sa&#287;l&#305;yor asl&#305;nda bu dei&#287;i&#351;imi. Yan&#305; s&#305;ra Akos ondan a&#287;r&#305; kesici yap&#305;m&#305;n&#305; ö&#287;retmeye kar&#351;&#305;l&#305;k Cyra&#39;dan dövü&#351; sanatlar&#305; dersi istedi&#287;inde Cyra&#39;da ya bu çocuk bu hareketleri benim üzerimde kullan&#305;rsa falan demeden ö&#287;retmeyi kabul ediyor. Yan yana geldiklerinde uluslar&#305;n&#305;n farkl&#305;l&#305;klar&#305;n&#305; ve tarihini incelemeden edemeyen çiftimiz bir süre sonra çevrelerini de istemeden etkilemeye ba&#351;l&#305;yorlar.</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Veronica Roth&#8217;u Uyumsuz serisinden tan&#305;m&#305;&#351;t&#305;k ve yine fark yaratacak bir seriyle de kar&#351;&#305; kar&#351;&#305;yay&#305;z. &#304;lk sayfalarda Bir &#304;z B&#305;rak kitab&#305;n&#305;n dilini çözmek zor ama kitab&#305;n arkas&#305;nda kurgulanm&#305;&#351; yabanc&#305; terimler için özel bir sözlük bulunuyor. Bir &#304;z B&#305;rak, beklenmedik arma&#287;anlarla dolu bir galakside, arkada&#351;l&#305;&#287;&#305;n -ve a&#351;k&#305;n- gücü üzerine sars&#305;c&#305; bir roman.</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(Kitap fiyat&#305; hakk&#305;nda bilgi sahibi olmak için kitap görselini t&#305;klayabilirsiniz.)</span></p>
</asp:Content>


<asp:Content ID="Content7" runat="server" contentplaceholderid="ContentPlaceHolder10">
    <a href="https://www.kitapyurdu.com/kitap/yuzuklerin-efendisi-tek-cilt/43196.html"> <img src ="yüzüklerinefendisi.jpg"></a> 
</asp:Content>
<asp:Content ID="Content8" runat="server" contentplaceholderid="ContentPlaceHolder9">
     <a href="https://www.kitapyurdu.com/kitap/bitmeyecek-oyku/439777.html"> <img src ="bitmeyeceköykü.jpg"></a> 
</asp:Content>
<asp:Content ID="Content9" runat="server" contentplaceholderid="ContentPlaceHolder8">
    <a href="https://www.kitapyurdu.com/kitap/bir-iz-birak/414119.html"> <img src ="birizb&#305;rak.jpg"></a> 
</asp:Content>



