<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="KisiselGelisim.aspx.cs" Inherits="FinalProject.KisiselGelisim"  MasterPageFile="~/Site2.Master" %>

<asp:Content ID="Content1" runat="server" contentplaceholderid="ContentPlaceHolder1">
    <p>

        <i style="color: rgb(105, 36, 6); font-family: Calibri; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b>Ki&#351;isel Geli&#351;im Kitaplar&#305;</b></i></p>
<p>

    <b style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Duygusal Zeka &#8211; Daniel Goleman</b></p>
</asp:Content>
<asp:Content ID="Content2" runat="server" contentplaceholderid="ContentPlaceHolder7">
    <p>

        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">IQ ile ölçülen zeka, insanlar&#305;n okul ve i&#351; ya&#351;am&#305;ndaki ba&#351;ar&#305;s&#305;n&#305; belirleyen de&#287;i&#351;mez bir etken midir? Öyleyse, neden yüksek IQ&#8217;lu çocuklar, ortalama IQ&#8217;ya sahip arkada&#351;lar&#305;na göre hayatta daha ba&#351;ar&#305;s&#305;z olabiliyor? Dr. Daniel Goleman, psikoloji alan&#305;nda ç&#305;&#287;&#305;r açan bu kitab&#305;nda, duygusal zekan&#305;n IQ&#8217;dan daha önemli oldu&#287;unu kan&#305;tl&#305;yor. Duygusal zekay&#305;, özbilinç, azim, dürtülerini frenleme, ba&#351;kalar&#305;n&#305;n duygular&#305;n&#305; payla&#351;abilme gibi özellikleri içeren bir zeka olarak 
        tan&#305;ml&#305;yor. Ara&#351;t&#305;rma bulgular&#305;na göre, duygusal zeka yoksunlu&#287;u, ki&#351;inin aile ya&#351;am&#305;ndan mesleki ba&#351;ar&#305;s&#305;na, toplumsal ili&#351;kilerinden sa&#287;l&#305;k durumuna kadar birçok alanda çok kötü sonuçlar do&#287;urabiliyor. Daniel Goleman bu kitab&#305;yla; duygusal zekan&#305;n IQ&#39;dan önemli oldu&#287;unu kan&#305;tlamaya çal&#305;&#351;&#305;rken oldukça güzel bir eser ortaya ç&#305;karm&#305;&#351;. Konuyu zengin örnekleriyle hem fiziksel, hem sosyal, hemde psikolojik aç&#305;dan incelemi&#351;. Hayat boyunca ya&#351;an&#305;lan olumlu, olumsuz her davran&#305;&#351;ta gösterilen tepki, tav&#305;r gibi davran&#305;&#351;larda hemen duygusal zeka devreye girer. Zaten girmedi&#287;i veya a&#351;&#305;r&#305; derecede girdi&#287;i durumlarda önemli bir s&#305;k&#305;nt&#305; söz konusu oldu&#287;undan duygusal zeka geli&#351;tirilmelidir. Ö&#287;renilebilen ve ö&#287;retilebilen bu zeka beynin olgula&#351;abilme süreciyle yak&#305;ndan ili&#351;kilidir. Çözüm ise &quot;psikolojik ba&#287;&#305;&#351;&#305;kl&#305;k a&#351;&#305;s&#305;&quot;. Buyurun okuyun!</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(Kitap fiyat&#305; hakk&#305;nda bilgi sahibi olmak için kitap görselini t&#305;klayabilirsiniz.)</span></p>
</asp:Content>
<asp:Content ID="Content3" runat="server" contentplaceholderid="ContentPlaceHolder3">
    <p>

        <b style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Negatif Limanlardan Pozitif Sulara &#8211; O&#287;uz Sayg&#305;n</b></p>
</asp:Content>
<asp:Content ID="Content4" runat="server" contentplaceholderid="ContentPlaceHolder6">
    <p>

        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Yazar kitab&#305;nda isteyen herkesin hayatta ba&#351;ar&#305;l&#305; olabilece&#287;ini bunun için mutlaka iyi bir niçini olmas&#305; gerekti&#287;ini, yol gösterici olarak da NLP (Neuro-Linguistic Programming)&#8217;i göstermektedir. &#8220;Beyninizdeki zincirleri k&#305;r&#305;n&#8221; adl&#305; ilk bölümde, yazar verdi&#287;i seminerler neticesinde insanlarda meydana gelen de&#287;i&#351;imin çok ilginç örne&#287;ini anlatmaktad&#305;r. Ayr&#305;ca hayat&#305;ndaki büyük de&#287;i&#351;ikliklere, topluluk önünde nas&#305;l konu&#351;may&#305; ö&#287;rendi&#287;ine, adanmak denilen kelimenin 
        hayat&#305;ndan canl&#305; örneklerle tarifine ve ba&#351;ar&#305;y&#305; anlat&#305;rken kendisinin nas&#305;l ba&#351;ard&#305;&#287;&#305;na de&#287;inmi&#351;tir. &#304;kinci bölümü NLP varsay&#305;mlar&#305; ile ilgili. &#8220;Hedefe do&#287;ru&#8221; adl&#305; üçüncü bölümde, bizlere hedef merkezli ya&#351;aman&#305;n insanlara kazand&#305;rd&#305;klar&#305;ndan söz etmektedir. &#8220;Sorular cevaplard&#305;r&#8221; adl&#305; dördüncü bölümde, bizleri biraz dü&#351;ünmeye sevk etmek için ba&#351;ar&#305; ve motivasyonla ilgili güzel sözleri dü&#351;ündürücü bilmecelere dönü&#351;türerek anlatmaktad&#305;r.</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(Kitap fiyat&#305; hakk&#305;nda bilgi sahibi olmak için kitap görselini t&#305;klayabilirsiniz.)</span></p>
</asp:Content>
<asp:Content ID="Content5" runat="server" contentplaceholderid="ContentPlaceHolder4">
    <p>

        <b style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Beynine Format At &#8211; M. Bar&#305;&#351; Muslu</b></p>
</asp:Content>
<asp:Content ID="Content6" runat="server" contentplaceholderid="ContentPlaceHolder5">
    <p>

        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">&#8220;Pozitif dü&#351;ün, hayallerin gerçek olsun&#8221; diyen, ki&#351;isel geli&#351;im kitaplar&#305;ndan farkl&#305; olarak, NeuroFormat yöntemiyle, bütün korkular&#305;ndan, fobilerinden, sigara ba&#287;&#305;ml&#305;l&#305;&#287;&#305;ndan, kilolar&#305;ndan kurtulman&#305;, kronik a&#287;r&#305;lar&#305;na, hayat&#305;n&#305; zorla&#351;t&#305;ran yanl&#305;&#351; inançlar&#305;na son vermeni sa&#287;l&#305;yor Bar&#305;&#351; Muslu bu kitab&#305;yla.</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Beynimizin ve bilinçalt&#305;m&#305;z&#305;n ne kadar güçlü oldu&#287;u sürekli söylenir. Ancak bilinçalt&#305; çok güçlü olsa da, ne yaz&#305;k ki çok da ak&#305;ll&#305; de&#287;il. Yapt&#305;&#287;&#305;m&#305;z en büyük yanl&#305;&#351;, onun mükemmel bir bilge oldu&#287;unu ve bir anda son haline geldi&#287;ini dü&#351;ünmek. Ancak bu do&#287;ru de&#287;il. Beynimiz yenilenmeden, &#351;u anki ihtiyaçlar&#305; planlanmadan bu hale gelmi&#351;. Ek yaz&#305;l&#305;mlar, yamalar daha eski programlara eklenmi&#351;. Milyonlarca y&#305;l önceki ihtiyaçlara cevap veren yaz&#305;l&#305;mlar hala çal&#305;&#351;maya devam 
        ediyor. Bir ba&#351;ka deyi&#351;le yeni programlar eskilerle beraber çal&#305;&#351;&#305;yor.</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(Kitap fiyat&#305; hakk&#305;nda bilgi sahibi olmak için kitap görselini t&#305;klayabilirsiniz.)</span></p>
</asp:Content>


<asp:Content ID="Content7" runat="server" contentplaceholderid="ContentPlaceHolder10">
    <a href="https://www.kitapyurdu.com/kitap/duygusal-zeka/1193.html"> <img src ="duygusalzeka.jpg"></a> 
</asp:Content>
<asp:Content ID="Content8" runat="server" contentplaceholderid="ContentPlaceHolder9">
    <a href="https://www.kitapyurdu.com/kitap/negatif-limanlardan-pozitif-sulara-/267857.html"> <img src ="nlps.jpg"></a> 
</asp:Content>
<asp:Content ID="Content9" runat="server" contentplaceholderid="ContentPlaceHolder8">
    <a href="https://www.kitapyurdu.com/kitap/beynine-format-at/289775.html"> <img src ="bfa.jpg"></a> 
</asp:Content>



