<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PolisiyeMacera.aspx.cs" Inherits="FinalProject.PolisiyeMacera" MasterPageFile="~/Site2.Master"  %>

<asp:Content ID="Content1" runat="server" contentplaceholderid="ContentPlaceHolder1">
    <p>

        <i style="color: rgb(105, 36, 6); font-family: Calibri; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b>Polisiye-Macera Kitaplar&#305;</b></i></p>
    <p>

        <b style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Gözlerini S&#305;ms&#305;k&#305; Kapat - John Verdon</b></p>
</asp:Content>



<asp:Content ID="Content2" runat="server" contentplaceholderid="ContentPlaceHolder7">
    <p>

        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">John Verdon'dan, ak&#305;l oyunlar&#305;n&#305;n iç içe geçti&#287;i, s&#305;ra d&#305;&#351;&#305; bir roman. New York&#8217;un en gözde dedektifiyken, bas&#305;n&#305;n kendisine yak&#305;&#351;t&#305;rd&#305;&#287;&#305; isimden hep rahats&#305;z olmu&#351;tu: Süper Dedektif. Bir bulmacayla kar&#351;&#305;la&#351;t&#305;&#287;&#305;nda, mutlaka çözmek isterdi. Gurney&#8217;e göre her bulmacan&#305;n çözümü için mutlaka bir ipucu vard&#305;. Peki ya bu sefer yoksa? Dü&#287;ün günü öldürülen bir gelin&#8230; Ve olaya tan&#305;kl&#305;k eden yüzlerce davetli. Cinayeti kimin i&#351;ledi&#287;i ortada, herkes kendinden emin ama ya hepsi 
        zekice bir illüzyonla yan&#305;lt&#305;l&#305;yorsa... Cinayet silah&#305; dahil birçok detayda sürpriz ak&#305;l oyunlar&#305;n&#305; gördü&#287;ünde, Gurney tam bir psikopatla kar&#351;&#305; kar&#351;&#305;ya oldu&#287;unu anlar. Gurney &#351;eytan&#305;n bile akl&#305;na gelmeyecek yöntemleri, sorular&#305; ve keskin bak&#305;&#351; aç&#305;s&#305;yla soru&#351;turmaya bamba&#351;ka bir boyut kazand&#305;racakt&#305;r. Kim daha zeki; Gurney mi, yoksa müthi&#351; bir illüzyondan ibaret katil mi? John Verdon&#8217;dan, ak&#305;l oyunlar&#305;n&#305;n iç içe geçti&#287;i, s&#305;ra d&#305;&#351;&#305; bir roman.</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">&#8220;Yine ilki kadar &#351;a&#351;k&#305;nl&#305;k verici bir olay ve yine dahice çözümler.&#8221; - Publishers Weekly</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">&#8220;John Verdon gizemli bir olay&#305;n ak&#305;l almaz örgüsünü i&#351;lerken hikayenin en beklenmedik an&#305;nda ortaya ç&#305;k&#305;veren, &#351;eytani bir kurnazl&#305;&#287;a sahip. Yazar&#305;n büyük ilgi gören AKLINDAN B&#304;R SAYI TUT kitab&#305;ndan sonra bekledi&#287;inize de&#287;ecek.&#8221; -Washington Post</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(Kitap fiyat&#305; hakk&#305;nda bilgi sahibi olmak için kitap görselini t&#305;klayabilirsiniz.)</span></p>
</asp:Content>




<asp:Content ID="Content3" runat="server" contentplaceholderid="ContentPlaceHolder3">
    <p>

        <b style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Kuzular&#305;n Sessizli&#287;i - Thomas Harris</b></p>
</asp:Content>
<asp:Content ID="Content4" runat="server" contentplaceholderid="ContentPlaceHolder6">
    <p>

        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Buffalo Bill lakab&#305;yla tan&#305;nan bir seri katil, baz&#305; kad&#305;nlar&#305;n pe&#351;ine dü&#351;mektedir. Katilin belli bir amac&#305; vard&#305;r ama cesetler farkl&#305; eyaletlerde bulundu&#287;u için kimse bunu kavrayamaz. FBI Akademisi&#8217;nde genç bir stajyer ö&#287;renci olan Clarice Starling, büronun davran&#305;&#351; bilimleri bölümünden Jack Crawford taraf&#305;ndan ça&#287;&#305;r&#305;l&#305;nca &#351;a&#351;&#305;rm&#305;&#351;t&#305;r. Görevi, çok zeki bir psikiyatr ve korkunç bir katil olan, Baltimore Ak&#305;l Hastanesi&#8217;nde tutularak kriminal cinnet aç&#305;s&#305;ndan yak&#305;ndan 
        izlenen Dr. Hannibal Lecter ile görü&#351;mektir. Lecter&#8217;&#305;n, katillerin zihin yap&#305;s&#305;yla ilgili öngörülerinin, Buffalo Bill&#8217;in izinin sürülmesine ve adam&#305;n yakalanmas&#305;na yard&#305;m edebilece&#287;i dü&#351;ünülmektedir. Zeki ve çekici bir kad&#305;n olan Starling, kendini Lecter gibi keskin zekâl&#305; biriyle garip ve yo&#287;un bir ili&#351;ki içinde bulunca sars&#305;l&#305;r. Adam&#305;n, Buffalo Bill ve genç kad&#305;n&#305;n kendisi hakk&#305;ndaki &#351;ifreli ipuçlar&#305;; Starling&#8217;i tüm okurlar&#305;n tüyler ürpertici ve son derece sürükleyici bulaca&#287;&#305; bir ara&#351;t&#305;rmaya sürükler. Büyük bir yarat&#305;c&#305;l&#305;k ve ustal&#305;kla kaleme al&#305;nm&#305;&#351; olan Kuzular&#305;n Sessizli&#287;i roman&#305; bir gerilim klasi&#287;idir.</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(Kitap fiyat&#305; hakk&#305;nda bilgi sahibi olmak için kitap görselini t&#305;klayabilirsiniz.)</span></p>
</asp:Content>
<asp:Content ID="Content5" runat="server" contentplaceholderid="ContentPlaceHolder4">
    <p>

        <b style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&#304;stanbul Hat&#305;ras&#305; - Ahmet Ümit</b></p>
</asp:Content>
<asp:Content ID="Content6" runat="server" contentplaceholderid="ContentPlaceHolder5">
    <span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Ahmet Ümit&#8217;in yazd&#305;&#287;&#305;, Everest Yay&#305;nlar&#305;&#8217;n&#305;n yay&#305;mlad&#305;&#287;&#305; &#304;stanbul Hat&#305;ras&#305; eseri okudukça ö&#287;reten, ö&#287;rettikçe &#351;a&#351;&#305;rtan bir eser. Daha esere ba&#351;lamadan te&#351;ekkür sayfas&#305;na bir göz att&#305;&#287;&#305;n&#305;zda eme&#287;in ve bilginin niteli&#287;ini görüyorsunuz. Okudu&#287;unuz tarihi, mimari, dini, felsefi her motif büyük bir ara&#351;t&#305;rman&#305;n ürünü. Ahmet Ümit, kitab&#305;n&#305;n ilk sayfalar&#305;nda okuru Byzantion&#8217;un kurucusu olan Kral Byzas ile kar&#351;&#305;la&#351;t&#305;r&#305;yor. Byzas, Tanr&#305; Posedion&#8217;a üç taraf&#305; denizlerle 
çevrili, bereketli topraklar&#305; verdi&#287;i için bir bo&#287;ay&#305; kurban ederken o döneme gidiyorsunuz. Kral, Tanr&#305;&#8217;ya ada&#287;&#305;n&#305; sunarken anlat&#305;lan bir seremoni var. Bo&#287;a ile kral göz göze geliyor. Kral her ne kadar etkilense de bu seremoniden ona bah&#351;edilen o topraklar&#305;n yerle bir olmamas&#305; için tanr&#305;lar&#305; memnun etmek zorunda oldu&#287;unu biliyor. &#304;&#351;te o anlat&#305;lan e&#351;siz &#351;ehir, &#304;stanbul&#8217;un ilk ad&#305;. Sa&#287;lam bir giri&#351;, di&#287;er k&#305;s&#305;mlar&#305;n heyecan&#305;n&#305;n garantisi olaca&#287;&#305;n&#305; daha buradan belli ediyor. Asl&#305;nda bu eseri polisiye s&#305;n&#305;f&#305;na koyup rafa kald&#305;rmak büyük hata olur. &#304;stanbul&#8217;un bilmedi&#287;imiz tarihini, kaybolmu&#351; eserlerini, ayakta kalan tarihi zenginliklerinin detayl&#305; hikayesini sunuyor okuyucuya. Hem heyecan hem de ö&#287;renmek isteyenler bu kitab&#305; mutlaka edinmeli.</span><br style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
<span style="color: rgb(0, 0, 0); font-family: Calibri; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 10px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 218, 160); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(Kitap fiyat&#305; hakk&#305;nda bilgi sahibi olmak için kitap görselini t&#305;klayabilirsiniz.)</span>
</asp:Content>





<asp:Content ID="Content7" runat="server" contentplaceholderid="ContentPlaceHolder10">
    <a href="https://www.kitapyurdu.com/kitap/gozlerini-simsiki-kapat/268301.html"> <img src ="gözlerinis&#305;ms&#305;k&#305;kapat.jpg"></a> 
</asp:Content>
<asp:Content ID="Content8" runat="server" contentplaceholderid="ContentPlaceHolder9">
    <a href="https://www.kitapyurdu.com/kitap/kuzularin-sessizligi/344893.html"> <img src ="kuzular&#305;nsessizli&#287;i.jpg"></a>
</asp:Content>
<asp:Content ID="Content9" runat="server" contentplaceholderid="ContentPlaceHolder8">
    <a href="https://www.kitapyurdu.com/kitap/istanbul-hatirasi/150074.html"> <img src ="istanbul.jpg"></a> 
</asp:Content>






